routes/admin.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Writer\PostController as WriterPostController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\TagController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\WriterController;

Route::group(['middleware' => ['isAdmin', 'auth'] ,'prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::get('/', DashboardController::class)->name('index');

    // Users
    Route::group(['prefix' => 'users', 'as' => 'users.'], function () {
        Route::get('/', [UserController::class, 'index'])->name('index');
    });

    // Writers
    Route::group(['prefix' => 'writers', 'as' => 'writers.'], function () {
        Route::get('/', [WriterController::class, 'index'])->name('index');
    });

    // Posts
    Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
        Route::get('/index', [PostController::class, 'index'])->name('index');
        Route::get('/writer', [WriterPostController::class])->name('writer');
        Route::get('/create', [PostController::class, 'create'])->name('create');
        Route::post('/', [PostController::class, 'store'])->name('store');
        Route::get('{post}/edit', [PostController::class, 'edit'])->name('edit');
        Route::put('{post}', [PostController::class, 'update'])->name('update');
        Route::delete('{post}', [PostController::class, 'destroy'])->name('destroy');
    });

    // Tags
    Route::resource('tags', TagController::class);

});

routes/web.php
<?php

use App\Http\Controllers\Dashboard\BillingController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\Pages\TagController;
use App\Http\Controllers\Pages\HomeController;
use App\Http\Controllers\Pages\PostController;
use App\Http\Controllers\Pages\AuthorController;
use App\Http\Controllers\Pages\CheckoutController;
use App\Http\Controllers\Pages\CommentController;
use App\Http\Controllers\Pages\MembershipController;
use App\Http\Controllers\Stripe\PaymentController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

require 'admin.php';

Route::get('/', HomeController::class)->name('home');

Route::get('/membership', [MembershipController::class, 'index'])->name('membership');
Route::get('/users', [UserController::class, 'index'])->name('users');
Route::get('/payments', [PaymentController::class, 'index'])->name('payments');
Route::post('/payments', [PaymentController::class, 'store'])->name('payments.store');

/*
    * Url: /billing/*
 */
Route::group(['prefix' => 'dashboard'], function () {
    Route::get('/billing', [BillingController::class, 'index'])->name('billing');
});

/* Name: Authors
 * Url: /authors/*
 * Route: authors.*
*/
Route::group(['prefix' => 'authors', 'as' => 'authors.'], function () {
    Route::get('/', [AuthorController::class, 'index'])->name('index');
    Route::get('/{user:name}', [AuthorController::class, 'show'])->name('show');
});

/* Name: Posts
 * Url: /posts/*
 * Route: posts.*
*/
Route::group(['prefix' => 'posts', 'as' => 'posts.'], function () {
    Route::get('/', [PostController::class, 'index'])->name('index');
    Route::get('/{post}', [PostController::class, 'show'])->name('show');
});

/* Name: Tags
 * Url: /tags/*
 * Route: tags.*
*/
Route::group(['prefix' => 'tags', 'as' => 'tags.'], function () {
    Route::get('/', [TagController::class, 'index'])->name('index');
    Route::get('/{tag}', [TagController::class, 'show'])->name('show');
});


/* Name: Comments
 * Url: /comments/*
 * Route: comments.*
*/
Route::group(['prefix' => 'comments', 'as' => 'comments.'], function () {
    Route::post('/', [CommentController::class, 'store'])->name('store');
});


/* Name: Comments
 * Url: /comments/*
 * Route: comments.*
*/
Route::group(['prefix' => 'replies', 'as' => 'replies.'], function () {
    Route::post('/', [CommentController::class, 'store'])->name('store');
});


Route::middleware(['auth:sanctum', 'verified'])->get('/dashboard', function () {
    return view('dashboard');
})->name('dashboard');

app/Models/Tag.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Tag extends Model
{
    use HasFactory;

    const TABLE = 'tags';

    protected $table = self::TABLE;

    protected $fillable = [
        'name',
        'slug',
        'image',
        'description',
    ];

    public function id(): int{
        return $this->id;
    }

    public function name(): string{
        return $this->name;
    }

    public function slug(): string{
        return $this->slug;
    }

    public function imagePath(): string{
        return $this->image;
    }

    public function description(): ?string{
        return $this->description;
    }

    public function getRouteKeyName()
    {
        return 'slug';
    }

}

app/Http/Controllers/Admin/TagController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Tag;
use App\Http\Requests\TagRequest;
use App\Jobs\CreateTag;
use App\Jobs\DeleteTag;
use App\Jobs\UpdateTag;

class TagController extends Controller
{

    public function __construct()
    {
        $this->authorizeResource(Tag::class, 'tag');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.tags.index',[
            'tags' => Tag::paginate(8),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.tags.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(TagRequest $request)
    {
        $this->dispatchSync(CreateTag::fromRequest($request));
        return redirect()->route('admin.tags.index')->with('success', 'Tag Created');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function show(Tag $tag)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function edit(Tag $tag)
    {
        return view('admin.tags.edit',compact('tag'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function update(TagRequest $request, Tag $tag)
    {
        $this->dispatchSync(UpdateTag::fromRequest($tag, $request));
        return redirect()->route('admin.tags.index')->with('success', 'Tag Updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Tag  $tag
     * @return \Illuminate\Http\Response
     */
    public function destroy(TagRequest $tag)
    {
        $this->dispatchSync(new DeleteTag($tag));
        return redirect()->route('admin.tags.index')->with('success', 'Tag Deleted');
    }
}

app/Http/Controllers/Pages/TagController.php
<?php

namespace App\Http\Controllers\Pages;

use App\Http\Controllers\Controller;
use App\Models\Post;
use App\Models\Tag;
use Illuminate\Http\Request;

class TagController extends Controller
{
    public function index()
    {
        return view('pages.tags.index', [
            'tags' => Tag::all(),
        ]);
    }

    public function show(Tag $tag)
    {
        return view('pages.tags.show',[
            'tag' => $tag,
            'posts' => Post::forTag($tag->slug())->paginate(2),
        ]);
    }
}

app/View/Components/AdminLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class AdminLayout extends Component
{
    /**
     * Get the view / contents that represent the component.
     *
     * @return \Illuminate\Contracts\View\View|\Closure|string
     */
    public function render()
    {
        return view('layouts.admin');
    }
}

resources/views/admin/tags/create.blade.php
<x-admin-layout>

    {{-- Header --}}
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-white">
            {{ __('Tags: Create') }}
        </h2>
    </x-slot>

    <section class="mx-6">
        <div class="p-8">
            <x-form action="{{ route('admin.tags.store') }}" has-files>
                <div class="space-y-8">
                    {{-- Image --}}
                    <div>
                        <x-form.label for="image" value="{{ __('Image') }}" />
                        <x-form.input id="image" class="block w-full mt-1" type="file" name="image"
                        :value="old('image')" required/>
                        <x-form.error for="image" />
                    </div>

                    {{-- Name --}}
                    <div>
                        <x-form.label for="name" value="{{ __('Name') }}" />
                        <x-form.input id="name" class="block w-full mt-1" type="text" name="name"
                        :value="old('name')" required/>
                        <x-form.error for="name" />
                    </div>

                    {{-- Description --}}
                    <div>
                        <x-form.label for="description" value="{{ __('Description') }}" />
                        <x-form.textarea id="description" class="block w-full mt-1" type="text" name="description"
                        :value="old('description')" required/>
                        <x-form.error for="description" />
                    </div>

                    {{-- Button --}}
                    <x-buttons.primary>
                        {{ __('Create') }}
                    </x-buttons.primary>
            </x-form>
        </div>
    </section>
</x-admin-layout>

resources/views/admin/tags/edit.blade.php
<x-admin-layout>

    {{-- Header --}}
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-white">
            {{ __('Tags: Create') }}
        </h2>
    </x-slot>

    <section class="mx-6">
        <div class="p-8">
            <x-form action="{{ route('admin.tags.update', $tag) }}" method="PUT" has-files>
                <div class="space-y-8">
                    {{-- Image --}}
                    <div>
                        <x-form.label for="image" value="{{ __('Image') }}" />
                        <x-form.input id="image" class="block w-full mt-1" type="file" name="image"
                        :value="old('image')"/>
                        <x-form.error for="image" />
                    </div>

                    {{-- Name --}}
                    <div>
                        <x-form.label for="name" value="{{ __('Name') }}" />
                        <x-form.input id="name" class="block w-full mt-1" type="text" name="name"
                        :value="$tag->name()"/>
                        <x-form.error for="name" />
                    </div>

                    {{-- Description --}}
                    <div>
                        <x-form.label for="description" value="{{ __('Description') }}" />
                        <x-form.textarea id="description" class="block w-full mt-1" type="text"
                        name="description"/>
                            {{ $tag->description() }}
                        </form-textarea>
                        <x-form.error for="description" />
                    </div>

                    {{-- Button --}}
                    <x-buttons.primary>
                        {{ __('Update') }}
                    </x-buttons.primary>
            </x-form>
        </div>
    </section>
</x-admin-layout>

resources/views/admin/tags/index.blade.php
<x-admin-layout>

    {{-- Header --}}
    <x-slot name="header">
        <h2 class="text-xl font-semibold leading-tight text-white">
            {{ __('Tags') }}
        </h2>
    </x-slot>

    <section class="px-6">
        <div class="overflow-hidden border-b border-gray-200">
            <table class="min-w-full">
                <thead class="bg-theme-blue-100">
                    <tr>
                        <x-table.head>Name</x-table.head>
                        <x-table.head>Slug</x-table.head>
                        <x-table.head class="text-center">Created At</x-table.head>
                        <x-table.head class="text-center">Action</x-table.head>
                    </tr>
                </thead>

                <tbody class="divide-y divide-gray-200 divide-solid">
                    @foreach ($tags as $tag)
                        <tr>
                            {{-- Name --}}
                            <x-table.data>
                                <div>{{ $tag->name() }}</div>
                            </x-table.data>
                            {{-- Slug --}}
                            <x-table.data>
                                <div>{{ $tag->slug() }}</div>
                            </x-table.data>
                            {{-- Created At --}}
                            <x-table.data>
                                <div class="text-center">
                                    {{ $tag->created_at }}
                                </div>
                            </x-table.data>
                            {{-- Action --}}
                            <x-table.data>
                                <div class="text-center">
                                    <a class="p-1 bg-blue-200" href="{{ route('admin.tags.edit', $tag) }}">
                                        Edit
                                    </a>
                                    <br>
                                    <x-form action="{{ route('admin.tags.destroy', $tag) }}" method="DELETE">
                                        <button class="p-1 bg-red-200" type="submit">
                                            Delete
                                        </button>
                                    </x-form>
                                </div>
                            </x-table.data>
                        </tr>
                    @endforeach
                </tbody>
            </table>
            <div class="text-center p-2 mt-6 bg-gray-200">
                {{ $tags->render() }}
            </div>
        </div>
    </section>
</x-admin-layout>